import json

dialogues = [
    "This is the first line of dialogue generated by Python.",
    "This is the second line of dialogue generated by Python.",
    "This is the third line of dialogue generated by Python."
]

print(json.dumps(dialogues))
